-- Moodloom MVP schema
-- Auth model: anonymous-by-default with optional email backup (same pattern as DreamWise)

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  anon_token UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  email TEXT UNIQUE,
  password_hash TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS projects (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_projects_user_id ON projects(user_id);

-- User-defined groupings within a project (e.g. "Design Inspiration", "Post
-- Ideas", "Video Direction") — raised during real dogfooding as a way to
-- separate everything living on one project's board once it grows past a
-- handful of items. Per-project (not global) since different projects may
-- need entirely different groupings; every project is seeded with a starter
-- set on creation (see routes/projects.js) but the list is fully editable —
-- there's no fixed enum, since the whole point is "we'll add more as we go."
CREATE TABLE IF NOT EXISTS categories (
  id SERIAL PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  position INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_categories_project_id ON categories(project_id);

-- "board_items" holds every captured reference (image, video link, generic link)
-- that lives on a project's fixed-grid board.
CREATE TABLE IF NOT EXISTS board_items (
  id SERIAL PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  source_url TEXT NOT NULL,
  media_type TEXT NOT NULL CHECK (media_type IN ('image', 'video', 'link')),
  title TEXT,
  thumbnail_url TEXT,
  embed_html TEXT,
  position INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- NULL = uncategorized (the default — nothing forces a category at capture
-- time). ON DELETE SET NULL: removing a category un-categorizes its items
-- rather than deleting them.
ALTER TABLE board_items ADD COLUMN IF NOT EXISTS category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_board_items_project_id ON board_items(project_id);
CREATE INDEX IF NOT EXISTS idx_board_items_category_id ON board_items(category_id);

-- Belt-and-suspenders for the duplicate-capture guard in boardItems.js: that
-- check-then-insert has a small race window (two near-simultaneous requests
-- for the same URL could both pass the SELECT before either INSERTs), so
-- this constraint is the actual backstop that makes a true duplicate
-- impossible at the database level, regardless of timing.
CREATE UNIQUE INDEX IF NOT EXISTS idx_board_items_project_url_unique
  ON board_items(project_id, source_url);

-- Minimal per-project workspace notes area (v1: text only, per MVP scope)
CREATE TABLE IF NOT EXISTS workspace_notes (
  id SERIAL PRIMARY KEY,
  project_id INTEGER NOT NULL UNIQUE REFERENCES projects(id) ON DELETE CASCADE,
  content TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Short-lived codes for pairing the browser extension to the SAME account the
-- web app is using. Fixes a real gap found during testing: without this, the
-- extension and web app each silently create their own separate anonymous
-- account, and a capture made in one never shows up in the other. A code is
-- generated by the (logged-in) web app and redeemed once by the extension.
CREATE TABLE IF NOT EXISTS pairing_codes (
  code TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

